# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('teams', '0003_auto_20160618_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(to='blogs.Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(related_name='_user_subscriptions_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
