# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, to='qanda.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, to='blogs.Entry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='_user_subscriptions_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
