# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sprint_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
