# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160619_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
